import React from 'react';
import Orders from '@/components/Orders';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Orders',
    description: 'Generated by create next app',
};

const OrdersPage = () => {
    return (
        <div>
            <h2>Приходы</h2>
            <Orders />
        </div>
    );
};

export default OrdersPage;
