import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '@/components/shared/Header';
import NavigationMenu from '@/components/shared/NavigationMenu';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.scss';
import StoreProvider from '@/redux/StoreProvider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <html lang='en'>
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                    <Header />
                    <main className='d-flex'>
                        <NavigationMenu />
                        <div className='content__wrapper col-9 col-sm-10 col-lg-11 p-3'>
                            {children}
                        </div>
                    </main>
                </body>
            </html>
        </StoreProvider>
    );
}
