import React from 'react';
import Products from '@/components/Products';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Products',
    description: 'Generated by create next app',
};

const ProductsPage = () => {
    return (
        <div>
            <h2>Продукты</h2>
            <Products />
        </div>
    );
};

export default ProductsPage;
